### POST - REGISTER
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@gmail.com",
    "password": "12345"
}

### POST - LOGIN
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "12345"
}

### GET - WHOAMI
GET http://localhost:3000/api/v1/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3MTU5MzIxODF9.JHSrLOYZHvgWQYjH9nbWondYlQXflvLJuLTcG43MU7M